import * as E from './engine.js';
const $=id=>document.getElementById(id), svg=$('board'),ctx=$('battle').getContext('2d');
const store={get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}};
let s=E.createGame(), selected=null, purchase=null, rotation=0, hover=null, dragging=null, last=performance.now(), toastTimer, ending=false, tick=0;
let settings=store.get('cw-settings',{sound:false,motion:true,speed:1}), best=store.get('cw-best',0), saved=store.get('cw-save',null);
const META={laser:{name:'光羽梟',role:'精準光束',color:'#6d9bba'},chain:{name:'電尾狐',role:'連鎖閃電',color:'#dab462'},mortar:{name:'栗砲熊',role:'範圍爆破',color:'#cb8871'},frost:{name:'霜葉兔',role:'緩速支援',color:'#85bda9'}};
const esc=x=>String(x).replace(/[&<>"']/g,a=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[a]));
function gearPath(r=36){let p='';for(let i=0;i<48;i++){let a=i*Math.PI/24,rr=(i%4===0||i%4===3)?r*.83:r;p+=(i?'L':'M')+(Math.cos(a)*rr).toFixed(2)+','+(Math.sin(a)*rr).toFixed(2)}return p+'Z'}
function face(type,x=0,y=0,scale=1){let m=META[type]||META.laser;let ears=type==='frost'?'<ellipse cx="-10" cy="-22" rx="6" ry="16"/><ellipse cx="10" cy="-22" rx="6" ry="16"/>':type==='mortar'?'<circle cx="-17" cy="-14" r="8"/><circle cx="17" cy="-14" r="8"/>':'<path d="M-21 1L-20-25 -5-15 5-15 20-25 21 1Z"/>';return `<g transform="translate(${x} ${y}) scale(${scale})" fill="${m.color}" stroke="#244740" stroke-width="2.5" stroke-linejoin="round">${ears}<ellipse cy="1" rx="22" ry="19"/><path d="M-18 0Q-10-10 0-1Q10-10 18 0L12 13Q0 21-12 13Z" fill="#fff2d2"/><ellipse cx="-8" cy="1" rx="3" ry="4" fill="#23473f" stroke="none"/><ellipse cx="8" cy="1" rx="3" ry="4" fill="#23473f" stroke="none"/><path d="M-3 7L0 11 3 7Z" fill="#b87f3b" stroke="none"/><path d="M-12 20L-18 30 0 26 18 30 12 20" fill="${m.color}"/></g>`}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2100)}
function sound(f=500){if(!settings.sound)return;try{const A=window.AudioContext||window.webkitAudioContext;let a=sound.a||(sound.a=new A),o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);o.frequency.value=f;g.gain.setValueAtTime(.04,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.12);o.start();o.stop(a.currentTime+.12)}catch{}}
function save(){if(s.phase==='build')store.set('cw-save',s);best=Math.max(best,s.phase==='won'?12:Math.max(0,s.wave-(s.phase==='wave'?1:0)));store.set('cw-best',best)}
function showModal(html){s.paused=true;$('modal-content').innerHTML=html;$('modal').showModal();render()}
function closeModal(){ $('modal').close();s.paused=false;render()}
function help(){showModal(`<div class="big-mark">✺</div><h2>讓齒輪，連起森林。</h2><p>上方的夜霧怪會向城牆前進。下方是你的動力工坊，只有接上金色核心的森衛才會攻擊。</p><ol><li>選一位商店森衛，再點空格購買。每組佔兩格。</li><li>點 ↻ 或按 R 旋轉方向；相鄰的齒輪會自動嚙合。</li><li>點已放置森衛，再點空格移動，也能拖曳。</li><li>離核心越近，動力加成越高。暗色＝斷電。</li><li>開始一波後鎖定配置；過關再用金幣擴建、強化或修牆。</li></ol><p>四種分工：光羽梟單體、電尾狐連鎖、栗砲熊範圍、霜葉兔緩速。第 4、8、12 波有巨獸。</p><button class="primary" id="close-help">開始組裝</button>`);$('close-help').onclick=closeModal}
function newGame(){s=E.createGame();selected=purchase=null;rotation=0;ending=false;store.set('cw-save',null);closeModal();save();render();toast('工坊重啟。先把新森衛接上核心！')}
function getPiece(){return s.pieces.find(p=>p.id===selected)}
function result(r,good){if(r?.ok===false){toast(({'That footprint is blocked or outside the board.':'齒輪重疊或超出邊界，換個空位試試。','Not enough coins.':'金幣不足。','The wall is already at full strength.':'城牆已是滿耐久。','Already at maximum level.':'已達最高等級。',collision:'齒輪重疊了，換個空位試試。',bounds:'超出工坊邊界。',funds:'金幣不足。',phase:'等這一波結束後再調整。'})[r.reason]||r.reason||'目前無法執行');return false}sound();if(good)toast(good);save();render();return true}
function handleCell(x,y){if(s.paused||s.phase!=='build')return;let hit=s.pieces.find(p=>E.cells(p).some(c=>c.x===x&&c.y===y));if(purchase){let r=E.buyPlace(s,purchase,x,y,rotation);if(result(r,'新森衛加入工坊！')){selected=r.piece?.id??s.pieces.at(-1).id;purchase=null;render()}return}if(selected){let p=getPiece();if(hit&&hit.id!==selected){selected=hit.id;rotation=hit.rot;render();return}if(!hit&&result(E.movePiece(s,selected,x,y,rotation),'齒輪已移動。')){render();return}}if(hit){selected=hit.id;rotation=hit.rot;render()}else{selected=null;render()}}
function boardPoint(e){let r=svg.getBoundingClientRect(),scale=Math.min(r.width/600,r.height/500),ox=(r.width-scale*600)/2,oy=(r.height-scale*500)/2;return{x:Math.floor((e.clientX-r.left-ox)/scale/100),y:Math.floor((e.clientY-r.top-oy)/scale/100)}}
svg.addEventListener('pointerdown',e=>{if(s.phase!=='build'||s.paused)return;let c=boardPoint(e),hit=s.pieces.find(p=>E.cells(p).some(q=>q.x===c.x&&q.y===c.y));dragging={startX:e.clientX,startY:e.clientY,cell:c,id:!purchase?hit?.id:null,moved:false};svg.setPointerCapture(e.pointerId)});
svg.addEventListener('pointermove',e=>{hover=boardPoint(e);if(dragging&&Math.hypot(e.clientX-dragging.startX,e.clientY-dragging.startY)>8){dragging.moved=true;if(dragging.id){selected=dragging.id;rotation=getPiece().rot}}renderBoard()});
svg.addEventListener('pointerup',e=>{let d=dragging,c=boardPoint(e);dragging=null;if(d?.moved&&d.id){result(E.movePiece(s,d.id,c.x,c.y,rotation),'齒輪已移動。')}else handleCell(c.x,c.y);hover=null;render()});svg.addEventListener('pointercancel',()=>{dragging=null;hover=null;renderBoard()});svg.addEventListener('pointerleave',()=>{if(!dragging){hover=null;renderBoard()}});
$('rotate').onclick=()=>{if(s.phase!=='build'||s.paused)return;let r=(rotation+1)%4;if(purchase){rotation=r;render();return}let p=getPiece();if(p){if(result(E.movePiece(s,p.id,p.x,p.y,r),'齒輪已旋轉。'))rotation=r;render()}else toast('先選商店森衛或盤上的齒輪。')};
$('upgrade').onclick=()=>{let p=getPiece();if(p)result(E.upgradePiece(s,p.id),'森衛強化完成！');else toast('先點選盤上的森衛。')};$('sell').onclick=()=>{let p=getPiece();if(p&&result(E.sellPiece(s,p.id),'已回收零件，退還部分金幣。')){selected=null;render()}};$('cancel').onclick=()=>{selected=purchase=null;render()};$('repair').onclick=()=>result(E.repairWall(s),'城牆修復完成。');
$('start').onclick=()=>{if(s.phase==='won'||s.phase==='lost'){newGame();return}if(s.phase!=='build')return;selected=purchase=null;if(result(E.startWave(s))){ending=false;render()}};
$('pause').onclick=()=>{if($('modal').open)return;s.paused=!s.paused;render()};$('help').onclick=help;
$('settings').onclick=()=>{showModal(`<h2>工坊設定</h2><label class="setting-row">音效 <input type="checkbox" id="sound-option" ${settings.sound?'checked':''}></label><label class="setting-row">動態齒輪 <input type="checkbox" id="motion-option" ${settings.motion?'checked':''}></label><label class="setting-row">戰鬥速度 <select id="speed-option"><option value="1">1× 標準</option><option value="2">2× 加速</option><option value="3">3× 快速</option></select></label><p>進度在每次整備時自動儲存在此瀏覽器。關閉戰鬥中頁面會回到該波整備前。</p><button class="primary" id="apply">返回工坊</button><button class="danger" id="reset">重新開始</button>`);$('speed-option').value=settings.speed;$('apply').onclick=()=>{settings={sound:$('sound-option').checked,motion:$('motion-option').checked,speed:Number($('speed-option').value)};store.set('cw-settings',settings);closeModal()};$('reset').onclick=()=>{showModal('<h2>重新上發條？</h2><p>目前這輪進度會清除，最高紀錄會保留。</p><button class="danger" id="confirm-reset">重新開始</button><button id="back">取消</button>');$('confirm-reset').onclick=newGame;$('back').onclick=closeModal}};
$('modal').addEventListener('cancel',()=>{s.paused=false;render()});document.addEventListener('keydown',e=>{if($('modal').open)return;if(e.key.toLowerCase()==='r')$('rotate').click();if(e.key==='Escape')$('cancel').click();if(e.code==='Space'){e.preventDefault();$('pause').click()}});document.addEventListener('visibilitychange',()=>{if(document.hidden&&s.phase==='wave'){s.paused=true;render()}});
function renderBoard(){let n=E.network(s),out='';for(let y=0;y<5;y++)for(let x=0;x<6;x++)out+=`<rect x="${x*100+6}" y="${y*100+6}" width="88" height="88" rx="18" fill="#c9ccb1" opacity=".5"/><circle cx="${x*100+50}" cy="${y*100+50}" r="3" fill="#a4b291"/>`;
let core=s.grid?.core||{x:2,y:2};out+=`<g transform="translate(${core.x*100+50} ${core.y*100+50})"><path d="${gearPath(45)}" fill="#d4a448" stroke="#8d733f" stroke-width="3"/><circle r="27" fill="#f2d784" stroke="#f9eeb4" stroke-width="3"/><text text-anchor="middle" y="10" fill="#947538" font-size="30">✺</text><text text-anchor="middle" y="39" fill="#6e673f" font-size="10" font-weight="700">核心</text></g>`;
for(let p of s.pieces){let connected=n.connectedIds.has(p.id),m=META[p.type]||META.laser,cs=E.cells(p),a=cs[0],b=cs[1]||a;out+=`<g opacity="${connected?1:.43}"><path d="M${a.x*100+50} ${a.y*100+50}L${b.x*100+50} ${b.y*100+50}" stroke="#385e52" stroke-width="55" stroke-linecap="round"/><path d="M${a.x*100+50} ${a.y*100+50}L${b.x*100+50} ${b.y*100+50}" stroke="${m.color}" stroke-width="45" stroke-linecap="round"/>`;
for(let [i,c] of cs.entries()){let spin=connected&&settings.motion?(tick*12*(i?-1:1))%360:0;out+=`<g transform="translate(${c.x*100+50} ${c.y*100+50})"><path transform="rotate(${spin})" d="${gearPath(43)}" fill="${m.color}" stroke="${selected===p.id?'#fffbe7':'#365b50'}" stroke-width="${selected===p.id?5:3}"/><circle r="28" fill="${i?'#ffffff24':'#375c5022'}" stroke="#ffffff35" stroke-width="2"/>${i?'<circle r="9" fill="#385f5260"/><circle r="3" fill="#e5ebcf"/>':''}</g>`}out+=face(p.type,a.x*100+50,a.y*100+43,.92);out+=`<rect x="${a.x*100+30}" y="${a.y*100+77}" width="40" height="15" rx="7" fill="#254e45"/><text x="${a.x*100+50}" y="${a.y*100+88}" text-anchor="middle" fill="#fff4cb" font-size="10">${connected?'⚡':'斷電 '}${p.level===1?'Ⅰ':p.level===2?'Ⅱ':'Ⅲ'}</text></g>`}
if(hover&&(purchase||dragging?.moved)){let p={type:purchase||getPiece()?.type,x:hover.x,y:hover.y,rot:rotation},valid=E.canPlace(s,p,selected);for(let c of E.cells(p)){if(c.x>=0&&c.y>=0&&c.x<6&&c.y<5)out+=`<rect x="${c.x*100+7}" y="${c.y*100+7}" width="86" height="86" rx="18" fill="${valid===true||valid?.ok?'#75b69270':'#d36c6270'}" stroke="#fff7ce" stroke-width="3"/>`}}
svg.innerHTML=out}
function render(){let n=E.network(s),p=getPiece(),build=s.phase==='build',wave=Math.min(12,s.wave+(build?1:0));$('coins').textContent=s.coins;$('hp').textContent=Math.ceil(s.wallHp);$('healthbar').style.width=s.wallHp+'%';$('wave').textContent=`第 ${wave} / 12 波`;$('power').textContent=`動力 ${n.connectedIds.size} / ${s.pieces.length}`;$('phase').textContent=s.paused?'已暫停':build?'整備回合':s.phase==='won'?'森林已守住':s.phase==='lost'?'城牆失守':'戰鬥中';$('weather').textContent=s.paused?'時間已停止':build?'工坊準備中':s.phase==='wave'?'夜霧來襲':'天亮了';$('chapter').textContent=`${String(wave).padStart(2,'0')} · ${wave<=4?'苔光入口':wave<=8?'蕨影長廊':'古樹之心'}${wave%4===0?' / 巨獸波':''}`;$('pause').textContent=s.paused?'▶':'Ⅱ';$('pause').setAttribute('aria-label',s.paused?'繼續':'暫停');$('banner').textContent=s.paused?'已暫停 · 點 ▶ 繼續':build?'把齒輪接上金色核心，讓森林醒來。':'';$('start').disabled=!build;$('start').innerHTML=build?`開始第 ${wave} 波 <span>→</span>`:'森衛守護中…';$('best').textContent=`最高紀錄 ${best} / 12`;
$('repair').disabled=!build||s.coins<25||s.wallHp>=100||s.paused;$('rotate').disabled=!build||s.paused;$('upgrade').disabled=!build||!p||p.level>=3||s.paused;$('sell').disabled=!build||!p||s.paused;
$('hint').textContent=purchase?`${META[purchase].name}：點空格放置 · 方向 ${['→','↓','←','↑'][rotation]} · 先旋轉再放也可以。`:p?`${META[p.type]?.name}已選取：點空格移動，或旋轉／強化。`:'先選守衛，再點空格。相鄰齒輪會傳遞動力。';
$('info').textContent=p?`${META[p.type]?.name} Lv.${p.level} · ${n.connectedIds.has(p.id)?'已通電':'未接上核心，無法攻擊'}${n.connectedIds.has(p.id)?` · 動力 ${Math.round((n.powerById.get(p.id)||1)*100)}%`:''} · ${p.level<3?'強化 ◈'+(E.upgradeCost?E.upgradeCost(p):Math.ceil(E.TYPES[p.type].cost*(.65+.35*p.level))):'已滿級'}`:purchase?`${META[purchase].role} · ${({laser:'穩定鎖定最接近城牆的敵人。',chain:'電弧跳躍攻擊三名鄰近敵人。',mortar:'對敵群造成範圍爆炸傷害。',frost:'使敵人減速，為其他森衛爭取時間。'})[purchase]}`:'兩格一組，旋轉可改變佔位。暗色守衛沒有接上核心。';
$('shop').innerHTML=Object.keys(META).map(t=>`<button data-type="${t}" ${!build||s.paused?'disabled':''} class="${purchase===t?'active':''}" aria-label="購買${META[t].name} ${E.TYPES[t].cost}金幣"><svg viewBox="-35 -38 70 76">${face(t)}</svg><strong>${META[t].name}</strong><small>${META[t].role} · ◈${E.TYPES[t].cost}</small></button>`).join('');$('shop').querySelectorAll('button').forEach(b=>b.onclick=()=>{purchase=b.dataset.type;selected=null;rotation=0;render()});renderBoard()}
function enemy(e){let x=70+e.y*460,y=260-e.x*230,scale=e.type==='boss'?1.55:e.type==='brute'?1.1:.85;ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);let wob=Math.sin(tick*7+Number(String(e.id).replace(/\D/g,'')))*2;ctx.translate(0,wob);ctx.fillStyle='#26434140';ctx.beginPath();ctx.ellipse(0,17,20,5,0,0,7);ctx.fill();ctx.strokeStyle='#263e3b';ctx.lineWidth=3;for(let i=-1;i<=1;i+=2){ctx.beginPath();ctx.moveTo(i*9,5);ctx.lineTo(i*23,1);ctx.lineTo(i*26,13);ctx.stroke()}ctx.fillStyle=e.type==='boss'?'#8a6e80':e.type==='brute'?'#8b9090':'#aab9ac';ctx.beginPath();ctx.ellipse(0,0,18,16,0,0,7);ctx.fill();ctx.stroke();ctx.fillStyle='#e4e8cf';ctx.beginPath();ctx.ellipse(0,2,12,10,0,0,7);ctx.fill();ctx.fillStyle='#375149';ctx.fillRect(-8,-2,5,6);ctx.fillRect(3,-2,5,6);if(e.type==='boss'){ctx.fillStyle='#d8b766';ctx.beginPath();ctx.moveTo(-16,-12);ctx.lineTo(-19,-27);ctx.lineTo(-5,-20);ctx.lineTo(0,-29);ctx.lineTo(6,-20);ctx.lineTo(19,-27);ctx.lineTo(15,-12);ctx.fill();ctx.stroke()}ctx.fillStyle='#213f3d';ctx.fillRect(-18,-25,36,4);ctx.fillStyle=e.slowUntil>s.time?'#a8e5d6':'#d4b66a';ctx.fillRect(-18,-25,36*Math.max(0,e.hp/e.maxHp),4);ctx.restore()}
function drawBattle(){ctx.clearRect(0,0,600,330);let g=ctx.createLinearGradient(0,0,0,330);g.addColorStop(0,'#315c51');g.addColorStop(1,'#74927a');ctx.fillStyle=g;ctx.fillRect(0,0,600,330);ctx.fillStyle='#a9ad8040';ctx.beginPath();ctx.moveTo(145,0);ctx.lineTo(455,0);ctx.lineTo(530,330);ctx.lineTo(70,330);ctx.fill();for(let i=0;i<7;i++){ctx.strokeStyle='#d0cda315';ctx.beginPath();ctx.moveTo(130-i*8,40+i*44);ctx.lineTo(470+i*8,40+i*44);ctx.stroke()}for(let i=0;i<12;i++){let side=i%2,x=side?570+(i%3)*7:24-(i%3)*5,y=(i*51)%330;ctx.fillStyle=i%3===0?'#224f44':'#3b6a53';ctx.beginPath();ctx.ellipse(x,y,40,60,.4,0,7);ctx.fill();ctx.fillStyle='#709577';ctx.beginPath();ctx.ellipse(x-12,y-15,7,11,.4,0,7);ctx.fill()}for(let i=0;i<12;i++){ctx.fillStyle='#e2d19066';ctx.beginPath();ctx.arc(80+(i*47)%450,30+(i*71+tick*(settings.motion?4:0))%260,1.5,0,7);ctx.fill()}for(let e of s.enemies)enemy(e);for(let sh of s.shots||[]){let p=s.pieces.find(p=>p.id===sh.pieceId),sx=80+(p?.x||2)*85,sy=330;ctx.globalAlpha=Math.max(0,sh.ttl/(sh.maxTtl||.25));ctx.strokeStyle=META[sh.type]?.color||'#f3ddb1';ctx.lineWidth=sh.type==='mortar'?6:3;for(let t of sh.targets||[sh.to]){let tx=70+t.y*460,ty=260-t.x*230;ctx.beginPath();ctx.moveTo(sx,sy);if(sh.type==='chain'){ctx.lineTo((sx+tx)/2+15,(sy+ty)/2);ctx.lineTo((sx+tx)/2-15,(sy+ty)/2-15)}ctx.lineTo(tx,ty);ctx.stroke();ctx.fillStyle=ctx.strokeStyle;ctx.beginPath();ctx.arc(tx,ty,sh.type==='mortar'?25:8,0,7);ctx.fill()}ctx.globalAlpha=1}ctx.fillStyle='#cfbd91';ctx.fillRect(0,311,600,19);ctx.fillStyle='#ece1ba';for(let i=0;i<13;i++)ctx.fillRect(i*48-10,299,34,22);ctx.fillStyle='#476c55';for(let i=0;i<6;i++){ctx.beginPath();ctx.moveTo(55+i*98,310);ctx.lineTo(66+i*98,323);ctx.lineTo(77+i*98,310);ctx.fill()}}
function finish(){ending=true;save();if(s.phase==='won'){store.set('cw-save',null);showModal('<div class="big-mark">☀</div><h2>發條不息，森林長明。</h2><div class="star-row">✦ ✦ ✦</div><p>十二波夜霧全部擊退。你把小小齒輪串成了一座不會熄滅的工坊。</p><p>城牆剩餘 '+Math.ceil(s.wallHp)+' · 森衛 '+s.pieces.length+' 位</p><button class="primary" id="again">再守護一次</button>')}else showModal('<div class="big-mark">☾</div><h2>夜霧暫時越過了城牆。</h2><p>試著增加通電的森衛，把緩速與範圍攻擊配在一起。也別忘了在整備時修牆。</p><button class="primary" id="retry">重試這一波</button><button id="again">重新開始</button>');$('again').onclick=newGame;if($('retry'))$('retry').onclick=()=>{let prev=store.get('cw-save',null);s=prev?.phase==='build'?prev:E.createGame();s.paused=false;ending=false;selected=purchase=null;closeModal();render()}}
function frame(now){let dt=Math.min(.05,(now-last)/1000);last=now;let phase=s.phase;if(!s.paused){tick+=dt;E.update(s,dt*settings.speed)}drawBattle();if(phase!==s.phase){save();render();if(s.phase==='build')toast('這一波守住了！補強齒輪再出發。')}if(s.phase==='wave'&&!s.paused){$('hp').textContent=Math.ceil(s.wallHp);$('healthbar').style.width=s.wallHp+'%';$('coins').textContent=s.coins}if(settings.motion&&Math.floor(now/90)!==Math.floor((now-dt*1000)/90))renderBoard();if((s.phase==='won'||s.phase==='lost')&&!ending)finish();requestAnimationFrame(frame)}
render();requestAnimationFrame(frame);if(saved?.phase==='build'&&saved.wave>0){showModal('<h2>工坊還在等你。</h2><p>已保存第 '+Math.min(12,saved.wave+1)+' 波前的整備進度。</p><button class="primary" id="resume">繼續守護</button><button id="fresh">新的冒險</button>');$('resume').onclick=()=>{s=saved;s.paused=false;closeModal();render()};$('fresh').onclick=newGame}else if(!store.get('cw-seen',false)){help();store.set('cw-seen',true)}
